In [2]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

```python
# 추가 인자를 사용할 때
model.add(SimpleRNN(hidden_size, input_shape =(timesteps, input_dim)))

# 다른 표기
model.add(SimpleRNN(hiden_size , input_length = M, input_dim =N))
```

In [3]:
model = Sequential()
model.add(SimpleRNN(3, input_shape = (2,10)))
#model.add(SimpleRNN(3, input_length = 2, input_dim =2))
model.summary()   # batch_size를 지정하지 않았으므로 output_shape = None,3

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [4]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape = (8,2,10)))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_1 (SimpleRNN)     (8, 3)                    42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


# Use Return Sequence

* ```return_sequences = True``` 로 지정할 경우 각 Seqquence 정보가 모두 return된다.

In [5]:
model = Sequential()
model.add(SimpleRNN(3, batch_input_shape = (8,2,10),return_sequences = True))
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (8, 2, 3)                 42        
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


# Python 으로 RNN구현 (numpy 사용)


$h_t = tanh(W_x X_t + W_h h_{t-1} + b)$

```python
hiddeen_state = 0 # 초기 은닉 상태를 0으로 초기화
for input_t in input_length:
  output_t = tanh(input_t,hidden_state_t) # 각 시점에 대해서 입력과 은닉 상태를 가지고 연산
  hidden_state_t = oupput_t # 계산 결과는 현재 시점의 은닉 상태가 된다. 
```



In [10]:
timesteps = 10
input_dim = 4
hidden_size = 8

#입력에 해당되는 2D 텐서를 선언
inputs = np.random.random((timesteps, input_dim))
print('input.shape :',input.shape)
print(input)
# 초기 은닉상태는 0벡터로 초기화

hidden_state_t = np.zeros((hidden_size,))
print("초기 Hidden state: ", hidden_state_t) # 8의 크기를 가지는 hidden_state , 현재는 초기 hidden_state로 모든 차원이 0

input.shape : (10, 4)
[[0.59479691 0.49924248 0.64177565 0.25460956]
 [0.49700584 0.32357646 0.6445936  0.15626557]
 [0.87452428 0.76530152 0.86205579 0.68169405]
 [0.92277907 0.68987344 0.98841264 0.55017798]
 [0.05198909 0.73907598 0.62855258 0.69164769]
 [0.46793178 0.52258718 0.29431136 0.54544343]
 [0.15897968 0.14772454 0.69476563 0.82702605]
 [0.27430565 0.67931147 0.02662915 0.80794611]
 [0.80810755 0.29208572 0.37619579 0.0629244 ]
 [0.76082179 0.50612497 0.0533281  0.1317132 ]]
초기 Hidden state:  [0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
Wx = np.random.random((hidden_size, input_dim)) #(8,4) 2D 텐서 생성 입력에 대한 가중치
Wh = np.random.random((hidden_size, hidden_size)) #(8,8) 2D 텐서 생성 hidden_state 에 대한 가중치
b = np.random.random((hidden_size)) #(8,)크기의 1D 텐서 생성 편향(bias)

In [8]:
print("Hidden state x 입력의 차원", Wx.shape)
print("Hidden state x의 hidden state_size",Wh.shape)
print("Hidden state size",b.shape)

Hidden state x 입력의 차원 (8, 4)
Hidden state x의 hidden state_size (8, 8)
Hidden state size (8,)


In [22]:
total_hidden_states = []

#메모리 셀 동작

for input_t in inputs: # 각 시점에 따라서 값이 입력됨.
  output_t = np.tanh(np.dot(Wx, input_t) + np.dot(Wh,hidden_state_t) + b)  # Wx*wt + Wh*Ht-1 +b
  total_hidden_states.append(list(output_t)) # 각 시점의 은닉 상태의 값을 저장
  hidden_state_t = output_t
  print(np.shape(total_hidden_states))


total_hidden_state = np.stack(total_hidden_states, axis =0)
print(f"timesteps, output_dim\n{total_hidden_state}")

(1, 8)
(2, 8)
(3, 8)
(4, 8)
(5, 8)
(6, 8)
(7, 8)
(8, 8)
(9, 8)
(10, 8)
timesteps, output_dim
[[0.99999895 0.99999898 0.99999556 0.99998519 0.99994257 0.99999427
  0.99998708 0.9997336 ]
 [0.99999574 0.99999485 0.99998552 0.99989681 0.99982494 0.99997008
  0.99989948 0.99932548]
 [0.99999697 0.9999988  0.99999257 0.99997346 0.99988456 0.99998598
  0.99998646 0.99977254]
 [0.99999267 0.9999899  0.99997895 0.9998243  0.99977416 0.99996711
  0.99987699 0.99924457]
 [0.99999788 0.99999724 0.99999116 0.99995091 0.99988957 0.99998282
  0.99995009 0.99946771]
 [0.9999873  0.99998813 0.99997501 0.99981278 0.99974704 0.99997545
  0.99991035 0.99946493]
 [0.99999393 0.9999922  0.99998308 0.99988122 0.99982919 0.99998191
  0.99989656 0.99941219]
 [0.99999929 0.99999916 0.9999959  0.99998411 0.99994005 0.99998965
  0.99997745 0.99960953]
 [0.9999956  0.99999551 0.99998751 0.99993086 0.9998548  0.9999837
  0.99996741 0.99957228]
 [0.9999986  0.99999874 0.99999421 0.99997658 0.99991757 0.99998792
  0

# 더 깊은 RNN

In [20]:
model = Sequential()
model.add(SimpleRNN(hidden_size, input_length = 10, input_dim = 5,return_sequences = True))
model.add(SimpleRNN(hidden_size,return_sequences = True))
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_4 (SimpleRNN)     (None, 10, 8)             112       
_________________________________________________________________
simple_rnn_5 (SimpleRNN)     (None, 10, 8)             136       
Total params: 248
Trainable params: 248
Non-trainable params: 0
_________________________________________________________________


# 임의의 입력으로  Simple RNN 생성

In [30]:
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional

In [32]:
train_x = [[0.1, 4.2, 1.5, 1.1, 2.8],
           [1.0, 3.1, 2.5, 0.7, 1.1],
           [0.3, 2.1, 1.5, 2.1, 0.1],
           [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_x))  #(input length = 4, input_dim =5) 
#단어 벡터의 차원은 5, 문장 길이 4  

(4, 5)


In [35]:
train_x = np.array([train_x], dtype = np.float32)
print(train_x.shape) #(batch_size, timestemp, input_dim)
 

(1, 4, 5)


In [36]:
rnn = SimpleRNN(3) # SimpleRNN(3,returun_sequences = False, return_state = False)

hidden_state = rnn(train_x)
print(hidden_state) # 마지막 시점의 hidden state만 출력됨. return_state = False 이므로

tf.Tensor([[-0.9625106   0.56625676  0.25280988]], shape=(1, 3), dtype=float32)


In [37]:
rnn = SimpleRNN(3, return_sequences=True)
hidden_state = rnn(train_x)
print(hidden_state)


tf.Tensor(
[[[-0.8771307  -0.9985161  -0.9810557 ]
  [-0.7368843  -0.676211   -0.9902401 ]
  [-0.31154245  0.32836664 -0.99786013]
  [ 0.81131905 -0.97089946 -0.1618344 ]]], shape=(1, 4, 3), dtype=float32)


In [42]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_state, last_state = rnn(train_x)
print('Hidden_states: \n',hidden_state)  # return_sequences = True 를 해서 모든 hidden_state출력
print("Last_state: \n",last_state) # return_state = True 로 해서 마지막 Hidden State출력

Hidden_states: 
 tf.Tensor(
[[[ 0.99977285 -0.99959993 -0.995973  ]
  [ 0.9986472  -0.09940516 -0.43017256]
  [ 0.99775946 -0.5924745   0.15106356]
  [ 0.93982494 -0.6383809   0.48495975]]], shape=(1, 4, 3), dtype=float32)
Last_state: 
 tf.Tensor([[ 0.93982494 -0.6383809   0.48495975]], shape=(1, 3), dtype=float32)


In [44]:
rnn = SimpleRNN(3, return_sequences = False, return_state = True)
hidden_state ,last_state= rnn(train_x)
print('Hidden_states: \n',hidden_state)  # return_sequences = False 를 해서 마지막 hidden_state출력
print("Last_state: \n",last_state) # return_state = True 로 해서 마지막 Hidden State출력

Hidden_states: 
 tf.Tensor([[ 0.99669045  0.99960685 -0.9606941 ]], shape=(1, 3), dtype=float32)
Last_state: 
 tf.Tensor([[ 0.99669045  0.99960685 -0.9606941 ]], shape=(1, 3), dtype=float32)


# LSTM 이해하기

In [46]:
lstm = LSTM(3, return_sequences=False, return_state = True)
hidden_state, last_state, last_cell_state = lstm(train_x)

print('hidden state', hidden_state)
print('last hidden state',last_state)
print('last cell state',last_cell_state)

hidden state tf.Tensor([[ 0.3433952  -0.08114029 -0.01159841]], shape=(1, 3), dtype=float32)
last hidden state tf.Tensor([[ 0.3433952  -0.08114029 -0.01159841]], shape=(1, 3), dtype=float32)
last cell state tf.Tensor([[ 1.2466607  -1.1358346  -0.03631247]], shape=(1, 3), dtype=float32)


In [47]:
lstm = LSTM(3, return_sequences=True, return_state = True)
hidden_state, last_state, last_cell_state = lstm(train_x)

print('hidden state', hidden_state)
print('last hidden state',last_state)
print('last cell state',last_cell_state)

hidden state tf.Tensor(
[[[-0.05799702 -0.00928712 -0.09264147]
  [ 0.24797131  0.40120435 -0.34797704]
  [ 0.12915172  0.70133984 -0.3671347 ]
  [ 0.04301834  0.41703197 -0.3616368 ]]], shape=(1, 4, 3), dtype=float32)
last hidden state tf.Tensor([[ 0.04301834  0.41703197 -0.3616368 ]], shape=(1, 3), dtype=float32)
last cell state tf.Tensor([[ 0.14483601  1.0765983  -1.135076  ]], shape=(1, 3), dtype=float32)


## LSTM 이해하기 2

In [49]:
x = np.array([[1,2,3],
             [2,3,4],
             [3,4,5],
             [4,5,6],
             [5,6,7],
             [6,7,8],
             [7,8,9],
             [8,9,10],
             [9,10,11],
             [10,11,12],
             [20,30,40],
             [30,40,50],
             [40,50,60]]
             )
y = np.array([4,5,6,7,8,9,10,11,12,13,50,60,70])
x.shape,y.shape

((13, 3), (13,))

In [50]:
x = x.reshape((x.shape[0],x.shape[1],1))
print(x.shape)

(13, 3, 1)


In [53]:
model = Sequential()
model.add(keras.layers.LSTM(20,activation = 'relu', input_shape = (3,1)))
model.add(keras.layers.Dense(5,activation = 'relu'))
model.add(keras.layers.Dense(1))

In [54]:
model.compile(optimizer='adam',loss = 'mse')


In [55]:
es = keras.callbacks.EarlyStopping(monitor  = 'loss', patience = 10,mode ='auto')
model.fit(x,y,epochs = 1000, batch_size =1, verbose =1, callbacks = [es])

Epoch 1/1000
13/13 [==============================] - 1s 7ms/step - loss: 645.2159
Epoch 2/1000
13/13 [==============================] - 0s 6ms/step - loss: 576.9808
Epoch 3/1000
13/13 [==============================] - 0s 5ms/step - loss: 465.7266
Epoch 4/1000
13/13 [==============================] - 0s 6ms/step - loss: 307.0421
Epoch 5/1000
13/13 [==============================] - 0s 6ms/step - loss: 167.8337
Epoch 6/1000
13/13 [==============================] - 0s 6ms/step - loss: 94.3931
Epoch 7/1000
13/13 [==============================] - 0s 6ms/step - loss: 26.8740
Epoch 8/1000
13/13 [==============================] - 0s 6ms/step - loss: 13.0177
Epoch 9/1000
13/13 [==============================] - 0s 6ms/step - loss: 6.8657
Epoch 10/1000
13/13 [==============================] - 0s 6ms/step - loss: 7.0169
Epoch 11/1000
13/13 [==============================] - 0s 6ms/step - loss: 6.9922
Epoch 12/1000
13/13 [==============================] - 0s 6ms/step - loss: 8.1799
Epoch 13/100

In [56]:
x_test = np.array([25,35,45])
x_test = x_test.reshape((1,3,1))

pred = model.predict(x_test)
pred

array([[55.212856]], dtype=float32)